// Complete authored project briefs adapted from source commit
// 003c7cc321dd758360c27575b8a9f2a4c7b710b7. Python is the supplied
// behavior to port; target-language references remain separate.
export const bridgeProjectBriefs = {
	syntax: [
		"# PTJ1 Syntax Translation Warmup",
		"",
		"## Purpose and contract",
		"",
		"Translate Python conditionals and helper functions into one typed target.",
		"`greeting(name)` returns `Hello, <name>!`, including an empty name.",
		"`absoluteValue(value)` returns the non-negative magnitude. The minimum signed",
		"integer has no positive `int` counterpart: reject it with an arithmetic/overflow",
		"exception. `isEven(value)` is true for all multiples of 2, including zero and",
		"negative even values. `fizzBuzzLabel(value)` returns `FizzBuzz` when divisible",
		"by both 3 and 5, `Fizz` for 3 only, `Buzz` for 5 only, otherwise decimal text.",
		"The combined branch must win. Java and C++ use the same helper names.",
		"",
		"Python starting behavior:",
		"```python",
		"def greeting(name):",
		'    return f"Hello, {name}!"',
		"def absolute_value(value):",
		"    if value == -2147483648:",
		'        raise OverflowError("magnitude does not fit in a 32-bit int")',
		"    return abs(value)",
		"def is_even(value):",
		"    return value % 2 == 0",
		"def fizz_buzz_label(value):",
		"    if value % 15 == 0:",
		'        return "FizzBuzz"',
		"    if value % 3 == 0:",
		'        return "Fizz"',
		"    if value % 5 == 0:",
		'        return "Buzz"',
		"    return str(value)",
		"```",
		"Python integers can grow; Java `int` is 32-bit. C++ `int` width is",
		"implementation-dependent; use the compiler's minimum value for its rejection",
		"check. Ordinary fixtures here fit both. Both typed ports must guard negation",
		"before applying it to the minimum value.",
		"",
		"## Checks",
		"",
		"Test names `Avery` and empty text; magnitudes -7, 0, 12 and minimum-int",
		"rejection; parity -2, -1, 0, 3; labels -15, -7, 0, 3, 5, 15 and 16.",
		"Java's bracketed collection display and C++'s space-separated display may differ;",
		"compare individual returned values, not incidental formatting.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	functions: [
		"# PTJ2 Function Port Pack",
		"",
		"## Purpose and contract",
		"",
		"Keep Python helper behavior while adding parameter and return types.",
		"`clampScore(score)` limits any integer to the inclusive range 0 through 100.",
		"`totalPrice(subtotal, member)` returns 90% of the subtotal for members and the",
		"unchanged subtotal otherwise. Subtotals are finite, non-negative doubles.",
		"`countVowels(text)` counts ASCII a/e/i/o/u, case-insensitively; repetitions count",
		"and y does not. Use ASCII text for shared Java/C++ fixtures: Java characters",
		"and C++ string bytes do not provide identical Unicode processing.",
		"",
		"Python starting behavior:",
		"```python",
		"def clamp_score(score):",
		"    return max(0, min(100, score))",
		"def total_price(subtotal, member):",
		"    return subtotal * 0.9 if member else subtotal",
		"def count_vowels(text):",
		'    return sum(letter.lower() in "aeiou" for letter in text)',
		"```",
		"A return type promises the kind of value produced on every reachable path.",
		"`void` is appropriate for a side effect with no returned value, not these",
		"helpers. `bool` in C++ and `boolean` in Java hold true/false values. Floating",
		"point results need a tolerance rather than exact decimal equality.",
		"",
		"## Checks",
		"",
		"Clamp -1, 0, 50, 100, 101 and the integer extremes. Price 0 and 42.5 with both",
		"membership values (member 42.5 is 38.25). Count empty text, `AEIOUaeiou`,",
		"`rhythm`, `Bridge Course` (5), and punctuation. Prove arguments remain unchanged.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	collections: [
		"# PTJ3 Text and Collection Port Lab",
		"",
		"## Purpose and contract",
		"",
		"Replace Python list operations with Java `List<String>`/`ArrayList<String>` or",
		"C++ `vector<string>`. `longWords(words)` returns a NEW collection containing",
		"words of length at least 5, preserving order and duplicates. `longestWord(words)`",
		"returns the FIRST longest word, or empty text for an empty collection. Neither",
		"helper changes its input. Shared fixtures contain ASCII strings; Java's UTF-16",
		"length and C++ byte length are not general Unicode character counts.",
		"",
		"Python starting behavior:",
		"```python",
		"def long_words(words):",
		"    return [word for word in words if len(word) >= 5]",
		"def longest_word(words):",
		'    return max(words, key=len, default="")',
		"```",
		"Java's supplied `List.of(...)` cannot be mutated. Build a new `ArrayList` for a",
		"result. C++ `const vector<string>&` borrows the input without copying the vector",
		"and prevents changing it through that reference. `add` and `push_back` append",
		"to the result. Valid indexes run from 0 through size minus one; an empty",
		"collection has no valid element index. A range loop avoids indexing here.",
		"",
		"## Checks",
		"",
		"Test empty and one-word collections, lengths 4/5/6, duplicates, all-short",
		"words, equal-length ties (`first`, `other` must select `first`) and the supplied",
		"sample. Verify order, retained duplicates and unchanged input. Compare returned",
		"elements; the drivers intentionally use different collection display styles.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	classes: [
		"# PTJ4 Shared Class Port",
		"",
		"## Purpose and contract",
		"",
		"Port a small stateful Python account into Java class files or C++ header/source",
		"files. Constructor `(owner, balance)` keeps the owner and a finite, non-negative",
		"starting balance; reject an invalid balance with an argument exception.",
		"`deposit(amount)` accepts finite positive amounts whose sum remains finite;",
		"otherwise throw an argument exception WITHOUT changing state.",
		"`withdraw(amount)` returns true and subtracts a finite positive affordable",
		"amount; otherwise returns false WITHOUT changing state. Zero transactions are",
		"invalid. `summary()` returns `<owner> has $<balance>` with exactly two decimal",
		"places using a decimal point, independent of machine locale.",
		"",
		"Python starting behavior:",
		"```python",
		"import math",
		"class BankAccount:",
		"    def __init__(self, owner, balance):",
		"        if not math.isfinite(balance) or balance < 0:",
		'            raise ValueError("invalid starting balance")',
		"        self.owner, self.balance = owner, balance",
		"    def deposit(self, amount):",
		"        if not math.isfinite(amount) or amount <= 0 or not math.isfinite(self.balance + amount):",
		'            raise ValueError("invalid deposit")',
		"        self.balance += amount",
		"    def withdraw(self, amount):",
		"        if not math.isfinite(amount) or amount <= 0 or amount > self.balance:",
		"            return False",
		"        self.balance -= amount",
		"        return True",
		"    def summary(self):",
		// eslint-disable-next-line no-template-curly-in-string -- Literal Python baseline.
		'        return f"{self.owner} has ${self.balance:.2f}"',
		"```",
		"This is a state/encapsulation exercise using doubles; production money handling",
		"needs a deliberate exact representation. Keep `balance` private. Java object",
		"variables hold references; assigning one to another does not clone the object.",
		"C++ account variables here hold values; copying one makes a separate account.",
		"The `.h` declares the interface; `.cpp` defines behavior; compile both source",
		"files to avoid missing-definition linker errors. `<utility>` declares `move`.",
		"",
		"## Checks",
		"",
		"125 + 25 - 40 yields `Avery has $110.00`. Test full withdrawal to zero,",
		"overdraft rejection, negative/zero/non-finite transactions, invalid starting",
		"balances, and deposit overflow. After every rejected transaction, the summary",
		"must be unchanged. Explain object aliasing versus value copying separately.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	java: [
		"# PTJ5 Python to Java Quiz Game",
		"",
		"## Purpose and contract",
		"",
		"Choose this exit branch when Java is the next course. Preserve a two-question",
		"Python console quiz while learning `Scanner`, line input and string equality.",
		"`scoreAnswer(answer, expectedAnswer)` returns 1 for a trimmed, case-insensitive",
		"content match, otherwise 0. Inputs are non-null ASCII text. The supplied driver",
		"asks for `class` and `equals`, accumulates points and prints `Final score: N/2`.",
		"EOF cancels remaining questions, prints `Input ended.`, and reports the score",
		"earned so far. An empty line is an incorrect answer; it is not EOF.",
		"",
		"Python starting behavior:",
		"```python",
		"def score_answer(answer, expected_answer):",
		"    return int(answer.strip().lower() == expected_answer.lower())",
		"score = 0",
		'for prompt, expected in [("What keyword defines a class in Java? ", "class"),',
		'                         ("What method compares string contents in Java? ", "equals")]:',
		"    try:",
		"        answer = input(prompt)",
		"    except EOFError:",
		'        print("Input ended.")',
		"        break",
		"    score += score_answer(answer, expected)",
		'print(f"Final score: {score}/2")',
		"```",
		"Java `==` compares String references; `equals` compares content and",
		"`equalsIgnoreCase` handles this ASCII case-folding contract. `nextLine` reads",
		"the entire answer. The supplied `hasNextLine` check handles cancellation before",
		"reading, so input exhaustion does not crash the program. Only the scoring",
		"helper is the implementation; prompts and input lifecycle are supplied.",
		"",
		"## Checks",
		"",
		"Run correct/correct, correct/wrong, wrong/wrong, surrounding spaces and mixed",
		"case, blank lines, immediate EOF and EOF after the first answer. Scores must",
		"stay between 0 and 2; cancellation must preserve points already earned.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	cpp: [
		"# PTJ6 Python to C++ Console Port",
		"",
		"## Purpose and contract",
		"",
		"Choose this exit branch when C++ is the next course. `scoreRound(guess,",
		"secretWords)` returns 1 for exact membership, otherwise 0; do not mutate the",
		"vector. Matching is case-sensitive. The supplied driver accepts at most three",
		"whitespace-delimited guesses against `vector`, `compile`, `header`. Repeating a",
		"matching word counts once per accepted round. EOF cancels remaining rounds:",
		"report `Input ended after N of 3 rounds.` and the score already earned. Failed",
		"input must never replay the previous guess.",
		"",
		"Python starting behavior for the helper:",
		"```python",
		"def score_round(guess, secret_words):",
		"    return int(guess in secret_words)",
		"```",
		"Python `input()` reads a full line; `cin >> guess` reads a whitespace-delimited",
		"token and skips blank whitespace. Thus `vector compile` supplies TWO C++ rounds",
		"and blank lines supply none. To port a line-based interface instead, use",
		"`getline` consistently and document that changed input contract. This pack",
		"deliberately teaches token input. `const string&` and `const vector<string>&`",
		"borrow inputs for reading; no manual allocation or raw pointers are needed.",
		"Includes declare library types/functions, and compilation must precede running.",
		"",
		"## Checks",
		"",
		"Test membership/non-membership, empty and duplicate secret lists, wrong case,",
		"three correct tokens, all incorrect tokens, repeated matches, blank whitespace,",
		"immediate EOF and EOF after ONE matching token. The last case must score 1,",
		"not 3. Print `Score: N` and keep the final score in the range 0 through 3.",
		"",
		"## Workflow and comparison",
		"",
		"Choose Java or C++ for the first pass; the other target is optional. The Python",
		"behavior below is the starting point, so the exercise is a port rather than a",
		"new algorithm. Predict results before editing. Keep function signatures and",
		"driver code, replace one unfinished body at a time, compile, then test the same fixtures.",
		"Starters compile but deliberately stop at an unfinished callable. Completed",
		"reference code is only in `solution/`; compare it after a working draft.",
		"",
		"Java: from the chosen `starter/java/` folder (or `starter/` for PTJ5), run",
		"`javac *.java` then `java Main`. Use JDK 21 or later. A public class named `Main`",
		"belongs in `Main.java`. C++: from `starter/cpp/` (or `starter/` for PTJ6), run",
		"`c++ -std=c++17 -Wall -Wextra -pedantic *.cpp -o bridge` then `./bridge`.",
		"PTJ4 needs both `.cpp` files and the header, not only `main.cpp`.",
		"In the site IDE, confirm the import, select the matching language, and keep the",
		"whole chosen-language folder together. Compile errors precede execution;",
		"runtime errors happen after compilation. Fix the first relevant diagnostic,",
		"then compare behavior rather than compiler-specific wording.",
		"",
		"## Guided use and completion evidence",
		"",
		"For independent study, read the contract, predict the listed cases, implement,",
		"and record actual versus expected results. In a facilitated session, pause at",
		"the same checkpoints to explain a type, loop, or state change before running.",
		"Record one compiler diagnostic, its cause and correction, all boundary cases,",
		"and one difference from Python. A passing sample alone is not completion.",
		"This authored bridge coursework preserves the PTJ project order."
	].join("\n"),
	capstone: [
		"# Task Tracker Capstone Port",
		"",
		"Choose Java **or** C++ and port the supplied Python task tracker. This authored",
		"bridge capstone combines functions, collection traversal, private object state,",
		"validation and a console command loop. It follows the original PTJ projects;",
		"completing both target languages is optional. It is not a GUI, persistence or",
		"production task-management project.",
		"",
		"The provided driver and state declarations compile before the six unfinished methods",
		"are implemented. An unfinished method raises an implementation reminder. Keep",
		"the target-language reference under `solution/` separate from the implementation.",
		"The Python program below is the starting behavior to translate, not a completed",
		"Java or C++ answer.",
		"",
		"## Files and build workflow",
		"",
		"- Java: import `starter/java`, containing `Main.java`, `TaskTracker.java` and this",
		"  brief. `Main` owns the supplied console loop; `TaskTracker` owns the the implementation.",
		"- C++: import `starter/cpp`, containing `main.cpp`, `TaskTracker.cpp`,",
		"  `TaskTracker.h` and this brief. Keep the header and both source files together.",
		"- The site's source workspace supports editing, saving and ZIP download. Extract",
		"  the ZIP before compiling. The Java browser runner is a limited beginner",
		"  preview; use a native JDK for this object-based capstone. C++ uses a native",
		"  compiler. Imported source does not execute automatically.",
		"- Java 21: from the extracted Java directory, run",
		"  `javac -Xlint:all Main.java TaskTracker.java`, then `java Main`.",
		"- C++17 on macOS/Linux: from the extracted C++ directory, run",
		"  `c++ -std=c++17 -Wall -Wextra -pedantic -I. main.cpp TaskTracker.cpp -o tracker`,",
		"  then `./tracker`. Unused-parameter warnings in untouched unfinished methods are",
		"  expected; compiler errors still need correction.",
		"- Python 3.9+: `python3 python/task_tracker.py` from this project root. The full",
		"  Python source is included below so the imported brief is self-contained.",
		"",
		"## Required public operations",
		"",
		"Use the provided camelCase Java/C++ signatures. Python uses snake_case names.",
		"Each tracker starts empty, with the next ID equal to 1. Its collection stores",
		"each task's ID, normalized title and done flag; new tasks start open.",
		"",
		"1. `normalizeTitle(title)` is a static helper. Trim only outer ASCII spaces",
		"   (U+0020), preserving case, punctuation, duplicate titles and internal spaces.",
		"   The normalized result must contain 1–60 printable ASCII characters (U+0020",
		"   through U+007E). Reject blank, tab/newline, non-ASCII, overlong and Java-null",
		"   titles with `title`. Return the normalized string without changing a tracker.",
		"2. `addTask(title)` normalizes before changing anything. Append an open task and",
		"   return its ID. Allocate IDs consecutively for **successful** adds; rejected",
		"   adds never consume an ID. Each tracker allows at most 100 successful adds",
		"   over its lifetime. A further valid add rejects with `limit`. Removing a task",
		"   never recycles its ID or restores this lifetime budget. Invalid titles still",
		"   reject with `title` when the budget is exhausted.",
		"3. `completeTask(id)` accepts a positive 32-bit integer. A nonpositive ID rejects",
		"   with `id` and changes nothing. Mark an existing open task done and return",
		"   true. Unknown IDs and already-done tasks return false without a change.",
		"4. `removeTask(id)` uses the same ID domain. Remove an existing task and return",
		"   true, preserving the order of the other tasks. Unknown IDs return false.",
		"5. `listTasks(openOnly)` accepts a Boolean and returns a **fresh** ordered list",
		"   of strings. Use `id | OPEN | title` or `id | DONE | title`, with exactly one",
		"   space on each side of each pipe. True includes only open tasks; false includes",
		"   all tasks. Return an empty list when none match. Editing the returned list",
		"   must not change the tracker.",
		"6. `summary()` returns exactly `Total: N | Open: O | Done: D` for the current",
		"   collection, where N = O + D. Removed tasks do not count. It changes nothing.",
		"",
		"Java rejects invalid values with `IllegalArgumentException`; C++ uses",
		"`std::invalid_argument`; Python uses `ValueError`. Their messages are the exact",
		"keys `title`, `id` or `limit` above. Typed Java/C++ API callers supply the declared",
		"argument types. Rejections preserve task titles, flags, order and next ID.",
		"Separate trackers have separate state. A Java/Python alias shares the same",
		"object; an ordinary C++ tracker copy has its own value state.",
		"",
		"## Supplied console protocol",
		"",
		"The driver is already implemented and may remain unchanged. Commands are",
		"case-sensitive, one per line. LF and CRLF line endings are accepted. `ADD ` takes",
		"the rest of the line as its title. `DONE ` and `REMOVE ` take a canonical positive",
		"decimal ID: no sign, leading zero, extra whitespace or value above 2147483647.",
		"",
		"| Command | Output after the opening help line |",
		"| --- | --- |",
		"| `ADD <title>` | `ADDED <id>` |",
		"| `DONE <id>` / `REMOVE <id>` | `CHANGED` or `UNCHANGED` |",
		"| `LIST` / `OPEN` | Each formatted row, or `(empty)` |",
		"| `SUMMARY` | The exact summary string |",
		"| `QUIT` | Stop without processing later lines |",
		"",
		"Invalid commands print `ERROR: command`; malformed/nonpositive console IDs print",
		"`ERROR: id`; rejected adds print `ERROR: title` or `ERROR: limit`. Continue after",
		"an error with unchanged state. EOF stops cleanly, including an unterminated last",
		"line. The program does not write files or require external services.",
		"",
		"## Checks",
		"",
		"For this input (outer spaces on the first title are intentional):",
		"",
		"```text",
		"SUMMARY",
		"ADD  Read notes",
		"ADD Read notes",
		"DONE 1",
		"DONE 1",
		"OPEN",
		"REMOVE 1",
		"ADD Plan check",
		"LIST",
		"SUMMARY",
		"QUIT",
		"ADD Ignored",
		"```",
		"",
		"After the opening help line, the output is:",
		"",
		"```text",
		"Total: 0 | Open: 0 | Done: 0",
		"ADDED 1",
		"ADDED 2",
		"CHANGED",
		"UNCHANGED",
		"2 | OPEN | Read notes",
		"CHANGED",
		"ADDED 3",
		"2 | OPEN | Read notes",
		"3 | OPEN | Plan check",
		"Total: 2 | Open: 2 | Done: 0",
		"```",
		"",
		"Also check a blank/title with a tab/non-ASCII title, exactly 60 versus 61 title",
		"characters, unknown and nonpositive IDs, an empty/all-done open filter, removal",
		"from the first/middle/last position, independent trackers and returned-list",
		"mutation. Reach the 100-add lifetime boundary, remove an item, and confirm the",
		"next valid add still rejects. Record state before each rejection and after it.",
		"Run the same LF, CRLF and EOF console fixtures in Python and the chosen target.",
		"",
		"## Walkthrough and completion",
		"",
		"1. Predict the sample outputs before running Python. Draw each state transition",
		"   and identify the next-ID value independently of collection size.",
		"2. Map the Python object/record/list representation into the provided target",
		"   declarations. Explain where the language requires explicit types and files.",
		"3. Implement normalization and one successful add. Verify a rejected add leaves",
		"   the next successful ID unchanged before adding other operations.",
		"4. Implement completion/removal, then filtering and summary. Check one normal",
		"   and one boundary case after each operation, including a fresh-output check.",
		"5. Compile and run the supplied command loop. Diagnose one compiler error and",
		"   one behavior mismatch using the same fixture in both languages.",
		"",
		"Completion requires one working target port, the shared output/edge-case record,",
		"unchanged-state evidence, exact build/run commands, and a short explanation of",
		"one type or object-model difference. During a walkthrough, pause at each checkpoint",
		"to predict the output, explain a trace, and independently",
		"correct the mismatch. Compare the separate reference only after a working draft.",
		"",
		"Optional extension: implement the second target language and compare Java",
		"reference aliasing with C++ value copying. Persistence, sorting or a GUI require",
		"a separately agreed behavior contract; none is required for this capstone.",
		"",
		"## Starting Python behavior",
		"",
		"The complete supplied source follows. It is also retained at",
		"`python/task_tracker.py` in this project.",
		"",
		"```python",
		'"""Supplied Python behavior to port; target-language answers live separately."""',
		"",
		"import sys",
		"",
		"",
		"class TaskTracker:",
		"    def __init__(self):",
		"        self._tasks = []",
		"        self._next_id = 1",
		"",
		"    @staticmethod",
		"    def normalize_title(title):",
		"        if not isinstance(title, str):",
		'            raise ValueError("title")',
		'        title = title.strip(" ")',
		"        if not 1 <= len(title) <= 60 or any(not 32 <= ord(c) <= 126 for c in title):",
		'            raise ValueError("title")',
		"        return title",
		"",
		"    def add_task(self, title):",
		"        title = self.normalize_title(title)",
		"        if self._next_id > 100:",
		'            raise ValueError("limit")',
		"        task_id = self._next_id",
		"        self._tasks.append([task_id, title, False])",
		"        self._next_id += 1",
		"        return task_id",
		"",
		"    def complete_task(self, task_id):",
		"        if type(task_id) is not int or not 1 <= task_id <= 2147483647:",
		'            raise ValueError("id")',
		"        for task in self._tasks:",
		"            if task[0] == task_id and not task[2]:",
		"                task[2] = True",
		"                return True",
		"        return False",
		"",
		"    def remove_task(self, task_id):",
		"        if type(task_id) is not int or not 1 <= task_id <= 2147483647:",
		'            raise ValueError("id")',
		"        for index, task in enumerate(self._tasks):",
		"            if task[0] == task_id:",
		"                del self._tasks[index]",
		"                return True",
		"        return False",
		"",
		"    def list_tasks(self, open_only):",
		"        if type(open_only) is not bool:",
		'            raise ValueError("filter")',
		"        return [f\"{i} | {'DONE' if done else 'OPEN'} | {title}\"",
		"                for i, title, done in self._tasks if not open_only or not done]",
		"",
		"    def summary(self):",
		"        done = sum(task[2] for task in self._tasks)",
		"        total = len(self._tasks)",
		'        return f"Total: {total} | Open: {total - done} | Done: {done}"',
		"",
		"",
		"def parse_id(raw):",
		'    if not raw or raw[0] == "0" or any(c not in "0123456789" for c in raw):',
		'        raise ValueError("id")',
		"    if len(raw) > 10 or int(raw) > 2147483647:",
		'        raise ValueError("id")',
		"    return int(raw)",
		"",
		"",
		"def main():",
		"    tracker = TaskTracker()",
		'    print("Task tracker. Commands: ADD <title>, DONE <id>, REMOVE <id>, LIST, OPEN, SUMMARY, QUIT.")',
		"    for line in sys.stdin:",
		'        line = line.removesuffix("\\n").removesuffix("\\r")',
		"        try:",
		'            if line == "QUIT":',
		"                break",
		'            if line.startswith("ADD "):',
		'                print(f"ADDED {tracker.add_task(line[4:])}")',
		'            elif line.startswith("DONE "):',
		'                print("CHANGED" if tracker.complete_task(parse_id(line[5:])) else "UNCHANGED")',
		'            elif line.startswith("REMOVE "):',
		'                print("CHANGED" if tracker.remove_task(parse_id(line[7:])) else "UNCHANGED")',
		'            elif line in ("LIST", "OPEN"):',
		'                rows = tracker.list_tasks(line == "OPEN")',
		'                print("\\n".join(rows) if rows else "(empty)")',
		'            elif line == "SUMMARY":',
		"                print(tracker.summary())",
		"            else:",
		'                raise ValueError("command")',
		"        except ValueError as error:",
		'            print(f"ERROR: {error}")',
		"",
		"",
		'if __name__ == "__main__":',
		"    main()",
		"```"
	].join("\n")
};
