// Authored CPPF1/CPPF2 briefs. Keep them aligned with the separately published
// CPP-Level-1 packs at 2864638dd25dc236c02a8e9c04f08eb6b32a9984.
// Starter code remains intentionally incomplete.
export const cppFoundationProjectBriefs = {
	madLibs: [
		"# CPPF1 Project 1: Mad Libs",
		"",
		"Use four string variables and console input to build a short story. This preserves",
		"the original Juni project goal: collect words and combine them into readable text.",
		"The required project belongs in CPPF1 after variables, strings and stream input.",
		"",
		"## Workspace and native run",
		"",
		"Start in `starter`, which contains an incomplete `main.cpp` and this brief. The",
		"initial program prints a TODO reminder and exits with status 2. Finish the TODOs",
		"in `main`; a successful completed run returns 0. Open `solution` only after a",
		"working attempt. The legacy root `main.cpp` forwards to the corrected reference",
		"for old direct build links; importing the whole root is not a starter workflow.",
		"",
		"With a C++20 compiler, run these commands inside either chosen folder:",
		"",
		"```sh",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The site IDE can import, edit, save and export the files. Its Build instructions",
		"control describes native compilation; it does not execute C++ in the browser.",
		"",
		"## Required behavior",
		"",
		"Read four nonempty whitespace-separated tokens in this order: animal, adjective,",
		"verb, second adjective. Prompt before each read with `Enter an animal: `,",
		"`Enter an adjective: `, `Enter a verb: `, and `Enter another adjective: `.",
		"Spaces and newlines both separate tokens; a multiword phrase becomes several",
		"tokens, so use one word for each field. Further tokens after the fourth are unused.",
		"",
		"Print a newline followed by this single story line, substituting the four values:",
		"",
		"```text",
		"Long, long ago lived a(n) ADJECTIVE ANIMAL. It would always VERB and was very SECOND_ADJECTIVE.",
		"```",
		"",
		"If input ends before all four tokens are read, write `Input incomplete.` and a",
		"newline to the error stream, return 1, and print no partial story. The supplied",
		"course readiness lesson explains checking an extraction with `if (!(std::cin >>",
		"word))`; the full branching topic follows in CPPF2. Failed input ends this run,",
		"so no stream recovery is needed inside this project.",
		"",
		"## Fixtures and walkthrough",
		"",
		"| Input tokens | Story |",
		"| --- | --- |",
		"| `fox curious jump brave` | `Long, long ago lived a(n) curious fox. It would always jump and was very brave.` |",
		"| `owl quiet glide wise` | `Long, long ago lived a(n) quiet owl. It would always glide and was very wise.` |",
		"| `fox curious` then end of input | Error, status 1, no story |",
		"",
		"1. Declare one string for each story field and explain what it stores.",
		"2. Add one prompt/read pair, compile, and confirm which token was captured.",
		"3. Repeat for the other fields; check the failed-read path before formatting.",
		"4. Build the story with insertion operators or string concatenation. Trace the",
		"   adjective/animal order rather than relying on the input order.",
		"5. Test both stories, newlines instead of spaces, empty input, and input ending",
		"   after each of the first three tokens. Present one customized story.",
		"",
		"Checkpoints work for individual study or an instructor-led walkthrough. Discuss",
		"why a token read stops at whitespace and how a full-line input task would differ.",
		""
	].join("\n"),
	chatBot: [
		"# CPPF1 Project 2: Chat Bot",
		"",
		"Build a text chatbot that greets a name, inserts a sneeze into a sentence, converts",
		"Fahrenheit to Celsius, and computes a sample currency conversion. These are the",
		"original Juni string and arithmetic goals. This required project follows Mad Libs.",
		"",
		"## Workspace and native run",
		"",
		"Use `starter/main.cpp` first. The supplied text/numeric input helpers are complete;",
		"leave them intact and implement the TODOs inside `main`. Their function mechanics",
		"are studied in CPPF3. The initial starter prints a reminder and returns 2. Compare",
		"with the separate `solution` only after a working attempt. The root `main.cpp`",
		"is a compatibility entry for the reference, not learner starter code.",
		"",
		"Inside the chosen starter or solution folder:",
		"",
		"```sh",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The site IDE provides confirmed import, editing, saving, ZIP export and native",
		"build instructions. It does not execute this C++ program in the browser.",
		"",
		"## Required input and behavior",
		"",
		"Enter four lines: name, sentence, Fahrenheit temperature, and US dollar amount.",
		"Name and sentence must be nonempty full lines; preserve their spaces and text.",
		"One-character and Unicode text are supported. LF and CRLF input both work.",
		"",
		"The numeric helper reads one whole line, rejects trailing non-whitespace text and",
		"non-finite numbers, and checks the inclusive bounds. Temperature is from -100 to",
		"300; dollar amount is from 0 to 1,000,000. Scientific notation is accepted. An",
		"input such as `32x`, `nan`, an empty line or an out-of-range value is rejected.",
		"Further input after all four fields is unused.",
		"",
		"Prompt for `Name: ` and `Sentence: `, then",
		"`Temperature in Fahrenheit [-100, 300]: ` and",
		"`Example US dollar amount [0, 1000000]: `.",
		"",
		"After all four fields are valid, print a newline and these four result lines:",
		"",
		"```text",
		"Hello, NAME!",
		"Sneeze: **achoo** SENTENCE",
		"Celsius: RESULT",
		"Example conversion at 109.01 JPY per USD: RESULT JPY",
		"```",
		"",
		'Use `sentence.insert(0, "**achoo** ")`. Position zero works even for short text',
		"and does not split a multibyte character. Celsius is `(Fahrenheit - 32) * (5.0 /",
		"9.0)`. The rate 109.01 is fictional fixed exercise data, not a current exchange",
		"rate. Multiply dollars by that rate. Print both numeric results with two decimal",
		"places using `std::fixed` and `std::setprecision(2)`. Binary floating-point values",
		"near rounding ties may show the neighboring last decimal; ordinary fixtures",
		"below avoid ties.",
		"",
		"A completed valid run returns 0. Stop at the first invalid field, return 1 and",
		"write exactly one newline-terminated error to the error stream: `Invalid name.`,",
		"`Invalid sentence.`, `Invalid temperature.`, or `Invalid amount.`. End of input",
		"counts as invalid at that field. Prompts already printed remain visible, but no",
		"greeting or conversion result is printed on an invalid run.",
		"",
		"## Fixtures and walkthrough",
		"",
		"| Four input lines | Expected result lines |",
		"| --- | --- |",
		"| `Ada Lovelace`, `I like rainy days.`, `32`, `1` | Greeting preserves the name; sneeze prefixes the entire sentence; `Celsius: 0.00`; sample conversion `109.01 JPY` |",
		"| `A`, `x`, `212`, `2` | Short text succeeds; `Sneeze: **achoo** x`; `Celsius: 100.00`; `218.02 JPY` |",
		"| `Sam`, `Hello`, `-40`, `0` | `Celsius: -40.00`; `0.00 JPY` |",
		"| `Sam`, `Hello`, `32x`, `1` | `Invalid temperature.`, status 1, no results |",
		"",
		"1. Trace how the supplied helpers differ from Mad Libs token extraction.",
		"2. Read and retain the two text fields, checking the helper's Boolean result.",
		"3. Read the two numeric fields with the listed bounds; test failure before math.",
		"4. Insert the prefix, compute the two values with doubles, then format the output.",
		"5. Test the fixtures, names/sentences containing spaces, a one-character sentence,",
		"   CRLF input, each missing field, and each numeric bound.",
		"6. Present a fictional conversation and explain the fixed rate's role as data.",
		"",
		"Self-check: integer division `5 / 9` loses the fractional multiplier. Explain why",
		"`5.0 / 9.0` is needed before comparing with the reference. No network lookup is",
		"needed for this fixed-data exercise.",
		""
	].join("\n"),
	numberGames: [
		"# CPPF2 Project 1: Number Games",
		"",
		"Practice both `for` and `while` loops by printing an inclusive integer range and",
		"computing sums and averages. This required project preserves the original Juni",
		"range-printing and two-loop goals; a sum alone does not complete the range task.",
		"",
		"## Workspace and native run",
		"",
		"Start with the incomplete `starter/main.cpp`. Keep its supplied `readInteger`",
		"helper and write the loop-based work in `main`. The helper's function structure",
		"is studied in CPPF3. The starter initially prints a reminder and returns 2.",
		"Use `solution` after a working attempt. The root entry forwards to the corrected",
		"reference for old build links and is not an importable starter folder.",
		"",
		"Run inside either chosen folder with a C++20 compiler:",
		"",
		"```sh",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The site IDE imports, edits, saves and exports the project. C++ runs natively",
		"using its Build instructions; it does not run inside the browser.",
		"",
		"## Input contract",
		"",
		"Input consists of whitespace-separated integer tokens. Read two range endpoints,",
		"then a count and that many values for a `for` batch, then a separate count and",
		"that many values for a `while` batch. Separate batches avoid introducing vectors",
		"before CPPF5. Extra tokens after both batches are unused. LF/CRLF input both work.",
		"",
		"- Endpoints are inclusive integers from -1000 to 1000.",
		"- Each batch count is from 0 to 100.",
		"- Each batch value is from -1,000,000 to 1,000,000.",
		"- Use `long long` accumulators. At most 100 bounded values keeps sums in range.",
		"- The supplied helper accepts signed decimal integers, including leading zeros;",
		"  it rejects partial integers such as `2x`, `2.5`, overflowing integers and missing",
		"  input. Numeric tokens longer than 64 characters are rejected.",
		"",
		"Print each ascending inclusive range and its sum once using `for`, then again",
		"using `while`. A reversed range is empty and has sum 0. A one-value range prints",
		"that value once. Do not swap reversed endpoints silently.",
		"",
		"For each batch print the sum and the arithmetic mean to two decimal places.",
		"Convert the sum to double before division. A zero count has sum 0 and average",
		"`undefined`; it never divides by zero. Results near floating-point rounding ties",
		"may show a neighboring last decimal.",
		"",
		"Prompts may appear alongside input. Required result lines use these labels:",
		"",
		"```text",
		"Range (for): VALUES",
		"Range sum (for): SUM",
		"Range (while): VALUES",
		"Range sum (while): SUM",
		"Sum (for): SUM",
		"Average (for): MEAN",
		"Sum (while): SUM",
		"Average (while): MEAN",
		"```",
		"",
		"Range values have one preceding space each and no trailing space. Use `empty`",
		"after a range label for reversed endpoints. Each completed result ends in a",
		"newline. Return 0 after both batches. On failure, stop immediately, return 1 and",
		"write one newline-terminated error to the error stream:",
		"",
		"- `Invalid integer input.` for missing, malformed or overflowing integer tokens.",
		"- `Invalid range.` for successfully parsed but out-of-bounds endpoints.",
		"- `Invalid count.` for a successfully parsed count outside 0–100.",
		"- `Invalid value.` for a successfully parsed batch value outside its bounds.",
		"",
		"Results from earlier completed phases can remain visible. Do not print the failed",
		"batch's sum or average. Do not consume later phases after an error.",
		"",
		"## Fixtures and walkthrough",
		"",
		"| Input tokens | Required results |",
		"| --- | --- |",
		"| `1 3 3 2 -1 5 2 4 6` | Both ranges `1 2 3`, range sums 6; first batch sum 6 / average `2.00`; second sum 10 / average `5.00` |",
		"| `5 2 0 0` | Both ranges `empty`, range sums 0; both batches sum 0 / average `undefined` |",
		"| `-2 -2 1 -5 1 5` | Both ranges `-2`, range sums -2; batch averages `-5.00` and `5.00` |",
		"| `1 3 -1` | `Invalid count.`, status 1; no batch result |",
		"| `1 3 1 2x` | `Invalid integer input.`, status 1; no batch result |",
		"",
		"1. Trace initialization, condition and update for the range loop on paper.",
		"2. Print the range using each loop kind, then add independent sum accumulators.",
		"3. Read the first batch with `for`; accumulate before calculating its mean.",
		"4. Repeat using `while` for the second batch. Identify the update that guarantees",
		"   termination and the variables that must be reset.",
		"5. Test normal, reversed, single-value, zero-count, missing and malformed cases,",
		"   then the numeric bounds. Explain why zero has no arithmetic mean here.",
		"6. Present one custom fixture and its predicted trace before running it.",
		""
	].join("\n"),
	rockPaperScissors: [
		"# CPPF2 Project 2: Rock, Paper, Scissors",
		"",
		"Use nested conditionals and Boolean expressions to choose the outcome of one",
		"two-player round. This is a required original Juni project in CPPF2. Randomness",
		"and computer opponents belong to later extensions, not this completion contract.",
		"",
		"## Workspace and native run",
		"",
		"Implement `starter/main.cpp` first. Its TODO reminder returns 2 until the program",
		"is completed. Keep decisions inside `main` for this conditionals lesson. Review",
		"the separate `solution` after a working attempt. The root entry forwards to that",
		"reference for old build links; import `starter`, not the mixed root.",
		"",
		"Inside the chosen folder:",
		"",
		"```sh",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The site IDE offers confirmed import, editing, saving, ZIP export and native",
		"build instructions. It does not execute C++ in the browser.",
		"",
		"## Required behavior",
		"",
		"Read two whitespace-separated tokens, player 1 first. Each must be exactly one",
		"of the lowercase strings `rock`, `paper`, or `scissors`. Spaces, LF and CRLF",
		"separate tokens. No case conversion is required. Extra tokens after the two",
		"choices are unused.",
		"",
		"Prompt with `Player 1 (rock, paper, scissors): ` and",
		"`Player 2 (rock, paper, scissors): `. If input ends before both tokens are read,",
		"write `Input incomplete.` and a newline to the error stream and return 1. After",
		"both reads, validate both choices before deciding a winner. If either is invalid,",
		"write `Invalid choice.` and a newline and return 1. Invalid inputs never award a",
		"win, including when both inputs are invalid.",
		"",
		"On valid input, print a newline followed by exactly one result line, then return",
		"0. Equal choices yield `Tie!`. Otherwise rock beats scissors, scissors beats",
		"paper and paper beats rock; print `Player 1 wins!` or `Player 2 wins!`.",
		"",
		"| Player 1 / Player 2 | rock | paper | scissors |",
		"| --- | --- | --- | --- |",
		"| rock | Tie! | Player 2 wins! | Player 1 wins! |",
		"| paper | Player 1 wins! | Tie! | Player 2 wins! |",
		"| scissors | Player 2 wins! | Player 1 wins! | Tie! |",
		"",
		"## Walkthrough and verification",
		"",
		"1. Read both tokens into separate strings and trace the stored values.",
		"2. Check input success, then validate the allowed-choice domain. Predict how a",
		"   capitalized choice such as `Rock` should behave.",
		"3. Handle equal choices, then use nested conditions for each remaining matchup.",
		"4. Test all nine table cells, an invalid first choice, an invalid second choice,",
		"   both invalid choices, empty input and input containing only one choice.",
		"5. Present a branch trace for a win, a loss, a tie and an invalid round.",
		"",
		"Self-check: swapping the two players should swap the winning player while ties",
		"stay ties. Validation must happen before the winner logic.",
		""
	].join("\n"),
	fizzBuzz: [
		"# CPPF2 Project 3: Fizz Buzz",
		"",
		"Print the integers 1 through 50 with divisibility substitutions. This required",
		"original Juni project combines a counted loop, remainder and ordered branching.",
		"",
		"## Workspace and native run",
		"",
		"Open `starter/main.cpp` first. Its counted loop is supplied; implement the",
		"decision and output inside the loop. The starter prints no result lines, reports",
		"its TODO on the error stream and returns 2. A completed version returns 0. Compare",
		"with `solution` after a working attempt. The legacy root `main.cpp` forwards to",
		"the corrected reference, which safely prints ordinary integer values.",
		"",
		"Inside either chosen folder:",
		"",
		"```sh",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The site IDE imports, edits, saves and exports C++ files and provides native",
		"build instructions. It does not execute this program in the browser.",
		"",
		"## Required behavior and fixtures",
		"",
		"The required version takes no input and prints exactly 50 newline-terminated",
		"lines, one per integer from 1 through 50 inclusive. Use these rules:",
		"",
		"- Multiples of both 3 and 5 print `FizzBuzz`.",
		"- Other multiples of 3 print `Fizz`.",
		"- Other multiples of 5 print `Buzz`.",
		"- All other values print the integer itself.",
		"",
		"Use exactly the shown capitalization, with no exclamation mark or extra blank",
		"line. Check the overlap before the individual divisibility cases. Ordinary",
		"values are integers; a pointer cast never converts an integer to display text.",
		"Send the number directly to the output stream. Successful runs have no error",
		"output and return 0.",
		"",
		"The first six lines are `1`, `2`, `Fizz`, `4`, `Buzz`, `Fizz`. Line 15 is",
		"`FizzBuzz`; line 30 is `FizzBuzz`; line 49 is `49`; line 50 is `Buzz`.",
		"",
		"## Walkthrough and optional extension",
		"",
		"1. Explain the loop initialization, inclusive end test and increment.",
		"2. Predict the remainder checks for 2, 3, 5 and 15 before writing branches.",
		"3. Implement the ordered checks and print one newline after each result.",
		"4. Verify all 50 lines against the rules, including the first and last line.",
		"   Explain why checking only the three special labels would miss a number-print",
		"   failure.",
		"5. Present a trace for one ordinary value and one overlap value.",
		"",
		"After the required version passes, the original bonus can be attempted by",
		"accepting two custom positive divisors. Define their bounds and reject zero",
		"before using `%`; predict cases where the two divisors are equal. This is an",
		"extension of the completed program, not another required project. The supplied",
		"reference and automated console fixture implement the fixed 3-and-5 version;",
		"they do not certify a learner's custom-divisor extension.",
		""
	].join("\n")
};

export const cppFoundationLessonBriefs = {
	setup: [
		"## A first compiled program",
		"",
		"Save this complete program as `main.cpp`:",
		"",
		"```cpp",
		"#include <iostream>",
		"",
		"int main() {",
		'    std::cout << "Hello, C++!\\n";',
		"    return 0;",
		"}",
		"```",
		"",
		"`#include <iostream>` makes stream declarations available. `main` is the entry",
		"point, braces enclose its body, and each statement ends with a semicolon.",
		"`std::cout` is the standard output stream; `<<` sends a value into that stream.",
		"`std::` selects a name in the standard-library namespace. `\\n` adds a newline;",
		"`std::endl` also adds one and flushes the stream. `return 0` reports success.",
		"",
		"With an installed C++20 compiler, open a terminal in the file's folder:",
		"",
		"```sh",
		"c++ --version",
		"c++ -std=c++20 -Wall -Wextra -Wpedantic main.cpp -o app",
		"./app",
		"```",
		"",
		"The compiler checks the source and creates the executable `app`; `./app` runs",
		"that executable. Recompile after every source edit, otherwise the old executable",
		"still runs. The expected output is `Hello, C++!` on one line. The site IDE lets",
		"the files be edited, saved and exported; its C++ Build instructions describe this",
		"native workflow and do not start a browser compiler.",
		"",
		"Remove one semicolon and compile again. This is a compile-time error: read the",
		"reported source line and fix it before running. A program that compiles can still",
		"produce the wrong result or fail at runtime, so a successful build does not prove",
		"the behavior. Restore the semicolon, change the greeting, rebuild and predict the",
		"new output before running it.",
		"",
		"Use `//` for a one-line comment or `/* ... */` for a block comment. Comments explain",
		"intent or temporarily disable source; commented code is not executed. Record",
		"the compiler version, exact build command, one corrected error and a fresh run",
		"as the initial readiness evidence.",
		""
	].join("\n"),
	values: [
		"## Declaring and using values",
		"",
		"A declaration gives a variable a type and name; initialization gives its first",
		"value. Assignment later replaces that value. Initialize values before reading",
		"them. The following complete program needs no input:",
		"",
		"```cpp",
		"#include <iostream>",
		"#include <string>",
		"",
		"int main() {",
		"    int age = 13;",
		"    age = 14;",
		"    double rating = 9.6;",
		"    bool warm = false;",
		"    char initial = 'A';",
		'    std::string word = "cat";',
		"    std::cout << age << '\\n' << rating << '\\n' << warm << '\\n';",
		"    std::cout << initial << '\\n' << word[0] << '\\n' << word.length() << '\\n';",
		"    std::cout << word + \" naps\" << '\\n';",
		"    std::cout << 10 / 3 << '\\n' << 10 % 3 << '\\n' << 10.0 / 3.0 << '\\n';",
		"    return 0;",
		"}",
		"```",
		"",
		"The result lines are `14`, `9.6`, `0`, `A`, `c`, `3`, `cat naps`, `3`, `1`, and",
		"approximately `3.33333`. An `int` stores whole numbers, a `double` stores a",
		"floating-point approximation, a `bool` stores true/false and prints 1/0 by default,",
		"and a `char` stores one character value. Single quotes denote a character;",
		"double quotes denote string text. Include `<string>` when using `std::string`.",
		"",
		"`+`, `-`, `*`, `/` perform arithmetic. Integer division discards the fractional",
		"part toward zero: `10 / 3` is 3. `%` is the integer remainder: `10 % 3` is 1.",
		"Use a nonzero divisor. Giving the operands floating-point types preserves a",
		"fractional quotient; this distinction matters in Chat Bot and Number Games.",
		"`static_cast<int>(rating)` would convert 9.6 to 9, discarding its fractional part.",
		"`const` marks a value that will not be reassigned.",
		"",
		"String indexes start at zero, and `word[0]` is valid here because `word` is nonempty.",
		"Never index an empty string or beyond its stored length. `length()` counts bytes;",
		"the reference's ASCII words make that count match the number of displayed letters.",
		'Concatenation joins strings. `sentence.insert(0, "**achoo** ")` inserts a prefix at',
		"a valid position even for short or Unicode text, which is the Chat Bot operation.",
		"",
		"`std::cin >> word` extracts a whitespace-separated token; leading whitespace is",
		"skipped and spaces stop the read. Mad Libs uses this behavior. `std::getline` reads",
		"the whole line and preserves spaces; Chat Bot uses supplied helpers built on it.",
		"The input lesson below explains failed reads and transitions between these forms.",
		"",
		"Predict each result before running the program. Then choose appropriate types for",
		"an item count, a temperature, a yes/no flag, a character initial and a sentence.",
		"The linked primitive-types program is a complete reference with its own output",
		"fixture, not an extra starter assignment.",
		""
	].join("\n"),
	input: [
		"## Token input, full-line input and failure",
		"",
		"Token extraction and a full-line read serve different contracts. After reading a",
		"number with `>>`, the line-ending character remains in the stream. Discard that",
		"line's remainder before reading the next line with `getline`:",
		"",
		"```cpp",
		"#include <iostream>",
		"#include <limits>",
		"#include <string>",
		"",
		"int main() {",
		"    int count = 0;",
		"    std::string sentence;",
		'    std::cout << "Count: ";',
		"    if (!(std::cin >> count)) {",
		"        std::cin.clear();",
		"        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\\n');",
		'        std::cerr << "Invalid count.\\n";',
		"        return 1;",
		"    }",
		"    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\\n');",
		'    std::cout << "Sentence: ";',
		"    if (!std::getline(std::cin, sentence) || sentence.empty()) {",
		'        std::cerr << "Missing sentence.\\n";',
		"        return 1;",
		"    }",
		'    std::cout << "\\n" << count << ": " << sentence << \'\\n\';',
		"    return 0;",
		"}",
		"```",
		"",
		"Input `3` on one line and `cats like naps` on the next produces the final result",
		"`3: cats like naps`. Missing or nonnumeric count input reports `Invalid count.`;",
		"a missing/empty second line reports `Missing sentence.`. Both errors return 1.",
		"",
		"The small `if` checks here are supplied input guards: the condition chooses a",
		"failure path. Full Boolean expressions and branching practice follow in CPPF2.",
		"`clear()` resets a failed stream's flags; `ignore(...)` discards the rest of the",
		"bad line. If a later retry were added, both operations would be needed before",
		"asking again. This demonstration ends after one failure and does not retry.",
		"",
		"Formatted numeric extraction can accept a prefix, such as the 3 in `3x`; this",
		"example intentionally discards the rest of that line. It is a stream-transition",
		"demonstration, not a strict whole-line numeric validator. Chat Bot's supplied",
		"helper validates a whole numeric line, and Number Games validates a whole token.",
		"Read those project contracts before choosing an input method. End of input also",
		"makes a read fail; a default-initialized value must not become a substitute for",
		"missing data.",
		"",
		"Test normal input, a sentence containing spaces, a nonnumeric count, empty input",
		"and a missing sentence. Explain which newline would otherwise become an empty",
		"`getline` result. Use LF input for this minimal stream-transition example; the",
		"reviewed Chat Bot helper also normalizes CRLF text lines.",
		""
	].join("\n"),
	branches: [
		"## Conditions and counted repetition",
		"",
		"Comparisons such as `==`, `!=`, `<`, `<=`, `>` and `>=` yield Boolean values.",
		"`&&` requires both conditions; `||` requires at least one; `!` negates a condition.",
		"`=` assigns a value and differs from `==`. An `if`/`else if`/`else` chain chooses",
		"the first matching branch. Braces keep the intended statements together.",
		"",
		"```cpp",
		"#include <iostream>",
		"",
		"int main() {",
		"    int score = 7;",
		"    if (score < 0 || score > 10) {",
		'        std::cout << "outside\\n";',
		"    } else if (score < 5) {",
		'        std::cout << "low\\n";',
		"    } else {",
		'        std::cout << "high\\n";',
		"    }",
		"    for (int number = 1; number <= 3; ++number) {",
		"        std::cout << number << '\\n';",
		"    }",
		"    return 0;",
		"}",
		"```",
		"",
		"This prints `high`, `1`, `2`, `3` on separate lines. Changing the score to -1 or",
		"11 selects `outside`; 0 and 4 select `low`; 5 and 10 select `high`. Explain why",
		"the domain check comes first. Rock/Paper/Scissors rejects",
		"invalid choices before deciding a winner, and Fizz Buzz checks its overlapping",
		"divisibility case before the individual cases.",
		"",
		"A `for` loop contains initialization, a Boolean stopping test and an update,",
		"separated by semicolons. Its body runs only while the test is true. `++number`",
		"adds one; `--number` subtracts one. `total += number` adds into an accumulator.",
		"Trace `number` at each test for the example. Starting at 4 would give zero",
		"iterations because the test `4 <= 3` fails immediately. Using `< 3` would omit 3.",
		"",
		"A `while` loop separates the same pieces: initialize before it, test in its",
		"condition and update inside its body. Without a progress-making update, a true",
		"condition can run forever. Start with a small finite trace and identify the",
		"termination argument before executing a learner-written loop.",
		"",
		"The linked for-loop program is a complete reference. It prints counted ranges,",
		"ASCII word characters forward/backward, sum 5050 and factorial 3628800, plus",
		"alternate loop forms. Read its README for the full output order. Compare it with",
		"the separate while-loop reference; then complete all three original CPPF2 projects.",
		""
	].join("\n")
};
