export const STATIC_MEDIA_BASE = "https://static.classes.jacobdanderson.net";
export const LEGACY_STATIC_MEDIA_BASE = "https://static.junilearning.com";
const STATIC_MEDIA_URL_PATTERN =
	/https:\/\/(?:static\.classes\.jacobdanderson\.net|static\.junilearning\.com)\/[^\s<>"')\]]+/g;
export const PENDING_STATIC_MEDIA_NOTICE_PATTERN =
	/\b(?:pending media|reserved|placeholder|not currently available|class static host)\b/i;

export const KNOWN_PENDING_STATIC_MEDIA_FILENAMES = [
	"aj_1_chatbot.mp4",
	"aj_2_array_practice.mp4",
	"aj_2_arraylist_practice.mp4",
	"aj_2_matrix_addition.mp4",
	"aj_2_sandwich_orders.mp4",
	"aj_2_test_scores.mp4",
	"aj_2_two_dimensional_array_practice.mp4",
	"aj_3_baked_good.mp4",
	"aj_3_student_class.mp4",
	"aj_4_divisible_by_7.mp4",
	"aj_4_recursion_practice.mp4",
	"aj_5_linear_search.mp4",
	"aj_6_binary_search.mp4",
	"aj_6_binary_search_recursion.mp4",
	"aj_6_precise_square_roots.mp4",
	"aj_7_biggest_smallest_bookshelf.mp4",
	"aj_7_insertion_sort.mp4",
	"aj_7_selection_sort.mp4",
	"aj_8_alphabetical_order.mp4",
	"aj_8_bubble_sort.mp4",
	"aj_9_merge.mp4",
	"aj_9_merge_sort.mp4",
	"aj_9_split.mp4",
	"aj_10_anything_array.mp4",
	"aj_10_exception_practice.mp4",
	"aj_10_juni_bakery.mp4",
	"aj_11_doubly_linked_list.mp4",
	"aj_11_linked_list.mp4",
	"aj_12_calculator_with_stacks.mp4",
	"aj_12_deque.mp4",
	"aj_12_queue.mp4",
	"aj_12_stack.mp4",
	"aj_12_valid_parenthesis.mp4",
	"aj_13_class_rank.mp4",
	"aj_13_letter_frequencies.mp4",
	"aj_14_basic_BST.mp4",
	"aj_14_BST.mp4",
	"aj_14_BST_traversals.mp4",
	"aj_15_hashmap.mp4",
	"aj_15_juni_search_engine.mp4",
	"aj_16_dijkstras_shortest_path.mp4",
	"aj_16_eulerian_mail_circuit.mp4",
	"aj_16_simple_graph.mp4",
	"aj_17_loading_data.mp4",
	"aj_17_street_searcher.mp4",
	"aj_17_weighted_graph.mp4",
	"aj_check-in_1.mp4",
	"aj_check-in_2.mp4",
	"aj_check-in_3.mp4",
	"aj_check-in_4.mp4",
	"am_12_file_io_with_dictionaries.mp4",
	"aa4_pset1_0.png",
	"aa5_pset2_0.png",
	"aa5_pset2_1.png",
	"aa5_pset2_2.png",
	"aa5_pset2_3.png",
	"aa5_pset2_4.png",
	"aa5_pset2_5.png",
	"aa5_pset2_6.png",
	"aa5_pset2_7.png",
	"aa5_pset2_8.png",
	"aa5_pset2_9.png",
	"aa5_pset2_10.png",
	"aa5_pset2_11.png",
	"aa5_pset2_12.png",
	"aa6_pset1_0.png",
	"aa6_pset1_1.png",
	"aa6_pset1_2.png",
	"aa6_pset1_3.png",
	"aa6_pset1_4.png",
	"aa6_pset2_0.png",
	"aa6_pset2_1.png",
	"aa6_pset2_2.png",
	"aa6_pset2_3.png",
	"aa6_pset2_4.png",
	"aa7_0.png",
	"aa7_pset1_0.png",
	"aa7_pset1_1.png",
	"aa7_pset1_2.png",
	"aa7_pset1_3.png",
	"aa7_pset1_4.png",
	"aa8_pset1_0.png",
	"aa8_pset1_1.png",
	"aa8_pset2_0.png",
	"aa8_pset2_sol0.png",
	"aa11_0.png",
	"aa11_1.png",
	"aa11_2.png",
	"aa11_3.png",
	"aa11_4.png",
	"ab_kickoff_0.png",
	"ab2_pset1_0.png",
	"ab2_concept2_0.png",
	"ab8_concept1_0.png",
	"ab8_concept1_1.png",
	"ab8_concept1_2.png",
	"ab8_concept1_3.png",
	"ab9_0.png",
	"ab9_1.png",
	"ab9_2.png",
	"ab10_pset1_0.png",
	"ab10_pset2_0.png",
	"ab10_pset2_2.png",
	"ab10_pset2_3.png",
	"ab10_pset2_4.png",
	"ab10_pset3_1.png",
	"ab10_pset3_3.png",
	"ab11_pset2_0.png",
	"ab11_pset2_1.png",
	"ab11_pset2_2.png",
	"ab11_pset2_3.png",
	"ab11_pset2_4.png",
	"ab11_pset2_5.png",
	"ab11_pset2_6.png",
	"ab11_pset2_7.png",
	"ab11_pset2_8.png",
	"ab11_pset2_9.png",
	"ab11_pset2_10.png",
	"ab11_pset2_11.png",
	"ab11_pset2_12.png",
	"ab11_pset2_13.png",
	"ab11_pset2_14.png",
	"ab11_pset2_15.png",
	"ab11_pset2_16.png",
	"ab11_pset2_17.png",
	"ab11_pset2_18.png",
	"ab11_pset2_19.png",
	"ab11_pset3_0.png",
	"ab11_pset3_1.png",
	"ab11_pset3_2.png",
	"ab11_pset3_3.png",
	"ab11_pset3_4.png",
	"ab11_pset3_5.png",
	"ab11_pset3_6.png",
	"ab11_pset3_7.png",
	"ab11_pset3_8.png",
	"ab11_pset3_9.png",
	"ab12_pset2_0.png",
	"ab12_pset2_1.png",
	"ab12_pset2_2.png",
	"ab13_concept1_0.png",
	"ab13_concept2_0.png",
	"ab15_pset1_0.png",
	"ab15_pset1_1.png",
	"ab15_pset1_2.png",
	"ab15_pset1_3.png",
	"ab15_pset1_4.png",
	"ab15_pset1_5.png",
	"ab15_pset1_6.png",
	"ab15_pset1_7.png",
	"ab15_pset1_8.png",
	"ab15_pset1_9.png",
	"ab15_pset1_10.png",
	"ab15_pset1_11.png",
	"ab15_pset1_12.png",
	"ab15_pset1_13.png",
	"ab15_pset1_14.png",
	"ab15_pset2_0.png",
	"ab15_pset2_1.png",
	"ab15_pset2_2.png",
	"ab15_pset2_3.png",
	"ab15_pset2_4.png",
	"ab15_pset2_5.png",
	"ab15_pset2_6.png",
	"ab15_pset2_7.png",
	"ab15_pset2_8.png",
	"ab15_pset2_9.png",
	"ab15_pset2_10.png",
	"ab15_pset2_12.png",
	"ab20_0.png",
	"ab20_1.png",
	"ab20_2.png",
	"ab20_3.png",
	"ab20_4.png",
	"check_in_1_length_0.png",
	"check_in_1_multiplication_0.png",
	"check_in_1_multiplication_1.png",
	"check_in_1_multiplication_3.png",
	"check_in_1_sums_0.png",
	"check_in_1_sums_1.png",
	"check_in_2_additional_0.png",
	"check_in_2_lines_0.png",
	"check_in_2_lines_2.png",
	"check_in_2_lines_4.png",
	"check_in_2_lines_5.png",
	"check_in_2_money_1.png",
	"check_in_2_multiplication_0.png",
	"check_in_2_multiplication_1.png",
	"check_in_2_multiplication_2.png",
	"check_in_2_time_0.png",
	"checkin1_app_0.png",
	"checkin1_fractions_0.png",
	"checkin1_fractions_1.png",
	"checkin2_app_0.png",
	"checkin2_gm_2.png",
	"checkin2_gm_3.png",
	"checkin2_gm_4.png",
	"checkin2_ma_0.png",
	"checkin2_app_2.png",
	"checkin2_app_3.png",
	"checkin2_app_4.png",
	"checkin2_app_5.png",
	"checkin2_advanced_0.png",
	"checkin2_advanced_1_updated.png",
	"checkin2_forms_0.png",
	"checkin2_inequalities_1.png",
	"checkin3_graphing_1.png",
	"ent4_project2_0.png",
	"fai1_project_1.mp4",
	"fai1_project_2.mp4",
	"fai1_project_3.mp4",
	"fai2_project_1.mp4",
	"FAI2_Project2_Updated.mp4",
	"fai3_project_1.mp4",
	"fai4_project_1.mp4",
	"fai4_project_2.mp4",
	"fai5_project_1.mp4",
	"fai5_project_2.mp4",
	"fai5_supplemental_project_1.mp4",
	"fai6_project_1.mp4",
	"fai6_project_2.mp4",
	"fai6_supplemental_project_1.mp4",
	"fai7_project_1.mp4",
	"fai7_project_2.mp4",
	"fai7_project_3.mp4",
	"fai8_project_1.mp4",
	"fai8_project_2.mp4",
	"fai9_project_1.mp4",
	"fai9_project_2.mp4",
	"fai9_project_3.mp4",
	"fai9_project_4.mp4",
	"fai10_project_1.mp4",
	"fai10_project_2.mp4",
	"fai10_project_3.mp4",
	"fai11_project_1.mp4",
	"fai3_1.png",
	"fai3_2.png",
	"fai3_4.png",
	"fai3_5.png",
	"fai3_6.png",
	"fai5_example.png",
	"fai6_1.png",
	"fai7_1.png",
	"fai7_2.png",
	"fai7_3.png",
	"fai7_4.png",
	"fai7_5.png",
	"fai7_6.png",
	"fai7_7.png",
	"fai9_1.png",
	"fai9_2.png",
	"fai9_3.png",
	"fai9_4.png",
	"fai9_5.png",
	"fai10_1.png",
	"fai10_2.png",
	"fai11_1.png",
	"jor2_disact_plotexample.png",
	"js1_chatbot.mp4",
	"js1_division_facts.mp4",
	"js1_first_middle_last.mp4",
	"js1_mad_libs.mp4",
	"js1_project_1.mp4",
	"js1_project_2.mp4",
	"js1_supplemental_project_1.mp4",
	"js1_supplemental_project_2.mp4",
	"js1_supplemental_project_3.mp4",
	"js2_basic_shapes.png",
	"js2_happy_graphics.png",
	"js2_project_1.mp4",
	"js2_project_2.mp4",
	"js2_project_3.mp4",
	"js2_rainbow.png",
	"js2_snowman.png",
	"js2_supplemental_project_1.mp4",
	"js2_supplemental_project_2.mp4",
	"js2_supplemental_project_3.mp4",
	"js2_temperature_converter.mp4",
	"js3_code_your_own_adventure.mp4",
	"js3_color_mixer.mp4",
	"js3_elevator_limits.mp4",
	"js3_project_1.mp4",
	"js3_project_2.mp4",
	"js3_project_3.mp4",
	"js3_spreadsheet_width.mp4",
	"js3_supplemental_project_1.mp4",
	"js3_supplemental_project_2.mp4",
	"js3_supplemental_project_3.mp4",
	"js3_too_chicken_to_cross_the_road.mp4",
	"js3_weather_activities.mp4",
	"js3_which_shape.mp4",
	"js4_checkout_calculator.mp4",
	"js4_letter_square.mp4",
	"js4_loops_practice.mp4",
	"js4_nested_loops.mp4",
	"js4_paintball.png",
	"js4_project_1.mp4",
	"js4_project_2.mp4",
	"js4_project_3.mp4",
	"js4_supplemental_project_1.mp4",
	"js5_letter_guesser.mp4",
	"js5_mathematical_challenges.mp4",
	"js5_number_guesser.mp4",
	"js5_project_1.mp4",
	"js5_project_2.mp4",
	"js5_project_3.mp4",
	"js5_supplemental_project_1.mp4",
	"js5_supplemental_project_2.mp4",
	"js5_supplemental_project_3.mp4",
	"js6_caught_speeding.png",
	"js6_methods_practice.png",
	"js6_min_and_max.png",
	"js6_palindrome_checker.png",
	"js6_picasso.png",
	"js6_project_1.mp4",
	"js6_project_2.mp4",
	"js6_project_3.mp4",
	"js6_string_expander.mp4",
	"js6_supplemental_project_1.mp4",
	"js6_supplemental_project_2.mp4",
	"js7_airline_management.mp4",
	"js7_arithmetic_sequence.mp4",
	"js7_fortuneteller.mp4",
	"js7_high_score_list.mp4",
	"js7_lucky_array.mp4",
	"js7_practice_with_arraylists.mp4",
	"js7_practice_with_arrays.png",
	"js7_project_1.mp4",
	"js7_project_2.mp4",
	"js7_project_3.mp4",
	"js7_song_shuffler.mp4",
	"js7_string_to_array.png",
	"js7_supplemental_project_1.mp4",
	"js7_supplemental_project_2.mp4",
	"js7_supplemental_project_3.mp4",
	"js7_too_much_reversing.png",
	"js8_2d_array_to_string.png",
	"js8_grid_drawer.mp4",
	"js8_magic_square.png",
	"js8_practice_with_2d_arrays.png",
	"js8_square_of_squares.mp4",
	"js9_advanced_battleship.mp4",
	"js9_simple_battleship.mp4",
	"jsm_check_in_project_1.mp4",
	"jsm_check_in_project_2.mp4",
	"jsm1_project_1.mp4",
	"jsm1_project_2.mp4",
	"jsm1_project_3.mp4",
	"jsm1_project_4.mp4",
	"jsm1_project_5.mp4",
	"jsm2_project_1.mp4",
	"jsm2_project_2.mp4",
	"jsm2_project_3.mp4",
	"jsm2_supplemental_project_1.mp4",
	"jsm2_supplemental_project_2.mp4",
	"jsm2_supplemental_project_3.mp4",
	"jsm2_supplemental_project_4.mp4",
	"jsm3_project_1.mp4",
	"jsm3_project_2.mp4",
	"jsm3_project_3.mp4",
	"jsm3_supplemental_project_1.mp4",
	"jsm4_project_1.mp4",
	"jsm4_project_2.mp4",
	"jsm4_project_3.mp4",
	"jsm4_supplemental_project_1.mp4",
	"jsm4_supplemental_project_2.mp4",
	"jsm5_project_1.mp4",
	"jsm5_project_2.mp4",
	"jsm5_project_3.mp4",
	"jsm5_project_4.mp4",
	"jsm5_supplemental_project_1.mp4",
	"jsm5_supplemental_project_2.mp4",
	"jsm6_project_1.mp4",
	"jsm6_project_2.mp4",
	"jsm6_project_3.mp4",
	"jsm6_supplemental_project_1.mp4",
	"jsm6_supplemental_project_2.mp4",
	"jsm7_project_1.mp4",
	"jsm7_project_2.mp4",
	"jsm7_project_3.mp4",
	"jsm7_supplemental_project_1.mp4",
	"jsm7_supplemental_project_2.mp4",
	"jsm8_project_1.mp4",
	"jsm8_project_2.mp4",
	"jsm8_project_3.mp4",
	"jsm9_project_1.mp4",
	"jsm9_supplemental_project_1.mp4",
	"jsm9_supplemental_project_2.mp4",
	"jsm9_supplemental_project_3.mp4",
	"jsm10_project_1.mp4",
	"jsm10_project_2.mp4",
	"jsm10_project_3.mp4",
	"jsm10_supplemental_project_1.mp4",
	"jsm12_project_1.mp4",
	"jsm12_project_2.mp4",
	"jsm12_supplemental_project_1.mp4",
	"jsm13_project_1.mp4",
	"jsm13_supplemental_project_1.mp4",
	"jsm14_project_1.mp4",
	"jm_1_dog_class.mp4",
	"jm_2_book_class.mp4",
	"jm_2_person_class.mp4",
	"jm_3_house_class.mp4",
	"jm_3_quiz_class.mp4",
	"jm_4_book_and_picturebook.mp4",
	"jm_4_lesson_and_dancelesson.mp4",
	"jm_4_rectangle_and_square.mp4",
	"jm_5_first_train_class.mp4",
	"jm_5_train_class.mp4",
	"jm_6_mrs_pacman.mp4",
	"jm_6_pacman_class.mp4",
	"jm_7_bubble_maker.mp4",
	"jm_7_click_circle.mp4",
	"jm_8_disco_ball.mp4",
	"jm_8_pacman_eater.mp4",
	"jm_8_pacman_eater_animated.mp4",
	"jm_9_block_game.mp4",
	"jm_9_disco_floor.mp4",
	"jm_9_falling_blocks.mp4",
	"jm_10_tic_tac_toe.mp4",
	"leb16_pset1_0.png",
	"leb16_pset1_2.png",
	"leb16_pset1_3.png",
	"maa1_pset1_0.png",
	"maa6_pset1_0.png",
	"maa6_pset1_1.png",
	"maa6_pset1_2.png",
	"maa6_pset1_3.png",
	"maa6_pset1_4.png",
	"maa7_pset1_0.png",
	"maa7_pset1_1.png",
	"maa7_pset1_10.png",
	"maa7_pset1_11.png",
	"maa7_pset1_2.png",
	"maa7_pset1_6.png",
	"maa7_pset1_7.png",
	"maa7_pset1_8.png",
	"maa7_pset1_9.png",
	"maa7_pset2_0.png",
	"maa7_pset2_1.png",
	"maa7_pset2_2.png",
	"maa7_pset2_3.png",
	"maa7_pset3_0.png",
	"maa7_pset3_1.png",
	"maa7_pset3_2.png",
	"maa7_pset3_3.png",
	"maa7_pset3_4.png",
	"maa7_pset3_5.png",
	"maa7_pset3_6.png",
	"maa7_pset3_7.png",
	"maa7_pset3_8.png",
	"maa7_pset3_9.png",
	"mfa18_pset1_0.png",
	"mfb14_pset1_0.png",
	"mfb14_pset1_1.png",
	"mfb14_pset1_2.png",
	"mfb14_pset1_3.png",
	"mfb14_pset1_4.png",
	"module_example.png",
	"msa1_concept1_mainideasupportingevidence.png",
	"msa15_concept2_transitionaldevices.png",
	"msa17_concept2_nemochart.png",
	"msa19_concept2_emptyplot.png",
	"msa19_concept2_labeledplot.png",
	"nw6_blank_narrative_arc.jpg",
	"nw6_narrative_arc_definitions.jpg",
	"jss8_project_1.mp4",
	"jss8_project_2.mp4",
	"jss8_project_3.mp4",
	"jss8_supplemental_project_1.mp4",
	"jss8_supplemental_project_2.mp4",
	"jss8_supplemental_project_3.mp4",
	"jss9_project_1.mp4",
	"jss9_project_2.mp4",
	"jss10_project_1.mp4",
	"jss10_project_2.mp4",
	"jss10_project_3.mp4",
	"jss10_supplemental_project_1.mp4",
	"jss10_supplemental_project_2.mp4",
	"jss11_project_1.mp4",
	"jss11_project_2.mp4",
	"jss11_project_3.mp4",
	"jss11_supplemental_project_1.mp4",
	"jss12_project_1.mp4",
	"jss12_project_2.mp4",
	"jss12_project_3.mp4",
	"jss12_project_4.mp4",
	"jss12_supplemental_project_1.mp4",
	"jss13_project_1.mp4",
	"jss13_project_2.mp4",
	"jss13_project_3.mp4",
	"jss13_project_4.mp4",
	"jss13_supplemental_project_1.mp4",
	"jss13_supplemental_project_2.mp4",
	"jss14_project_1.mp4",
	"jss14_project_2.mp4",
	"jss14_project_3.mp4",
	"jss14_project_4.mp4",
	"jss14_supplemental_project_1.mp4",
	"jss14_supplemental_project_2.mp4",
	"jss15_project_1.mp4",
	"jss15_supplemental_project_1.mp4",
	"jss15_supplemental_project_2.mp4",
	"jss15_supplemental_project_3.mp4",
	"jss_check_in_1_project.mp4",
	"jss_check_in_2_project.mp4",
	"check_in_2_starter.py",
	"check_in_3_starter.py",
	"pyg_3_asteroid_dodge.mp4",
	"pyg_3_light_control.mp4",
	"pyg_3_zrect_art.mp4",
	"pyg_7_beach_ball_dodge.mp4",
	"pyg6_platformer_game.py",
	"ps10_field_day.gif",
	"ps10_field_day_ii.gif",
	"ps10_todo_list.gif",
	"ps10_us_capitals_quiz.gif",
	"ps11_bank_account.gif",
	"ps11_calculator.gif",
	"ps11_juni_world.gif",
	"ps12_review_sentiment.gif",
	"ps12_type_racer.mp4",
	"ps13_advanced_typewriter_monkeys.gif",
	"ps13_typewriter_monkeys.gif",
	"ps13_wordsmith.gif",
	"ps14_advanced_blackjack.gif",
	"ps14_blackjack.gif",
	"ps14_game_of_war.gif",
	"ps1_index_picker.mp4",
	"ps1_mad_libs.gif",
	"ps1_relay_race.gif",
	"ps1_space_mountain.gif",
	"ps1_tip_calculator.gif",
	"ps2_calendar_machine.gif",
	"ps2_change_machine.gif",
	"ps2_crazy_nametags.gif",
	"ps2_debugging_loops.gif",
	"ps2_double_or_nothing.gif",
	"ps2_for_loop_fun.gif",
	"ps2_interest_aggregator.gif",
	"ps2_juni_archery.gif",
	"ps2_multiplication_tables.gif",
	"ps2_password_guesser.gif",
	"ps3_ascii_art.gif",
	"ps3_caesar_cipher.gif",
	"ps3_nested_boxes.gif",
	"ps3_password_cracker.gif",
	"ps3_simple_cipher.gif",
	"ps3_uppercase_to_lowercase.gif",
	"ps4_carnival_strength_tester.gif",
	"ps4_credit_card_validator.gif",
	"ps4_debugging_conditionals.gif",
	"ps4_fizzbuzz.gif",
	"ps4_joes_donuts.gif",
	"ps4_number_guesser.gif",
	"ps4_relay_race_statistics.gif",
	"ps4_rock_paper_scissors.gif",
	"ps4_test_statistics.gif",
	"ps5_coin_flipper.gif",
	"ps5_debugging_functions.gif",
	"ps5_dice_roller.gif",
	"ps5_functions_practice.gif",
	"ps5_juni_latin.gif",
	"ps5_number_games.gif",
	"ps6_basketball_stars.gif",
	"ps6_card_shuffler.mp4",
	"ps6_debugging_lists.gif",
	"ps6_dog_breeds.gif",
	"ps6_lists_practice.gif",
	"ps6_song_generator.gif",
	"ps6_stock_trader.gif",
	"ps6_tower_of_terror.gif",
	"ps7_birthday_converter.gif",
	"ps7_coffee_shop.gif",
	"ps7_debugging_dictionaries.gif",
	"ps7_dictionaries_practice.gif",
	"ps7_dictionary_indexing.gif",
	"ps7_song_generator_2.gif",
	"ps7_test_scores.gif",
	"ps8_morse_code.gif",
	"ps9_class_registration.gif",
	"ps9_class_registration_ii.gif",
	"ps9_debugging_sets.gif",
	"ps9_favorite_foods.gif",
	"ps9_sets_practice.gif",
	"ps9_soccer_nationalities.gif",
	"ps_12_evil_hangman.mp4",
	"ps_14_mastermind.mp4",
	"ps_15_master_project.mp4",
	"ps_9_wheel_of_fortune.mp4",
	"python_level_2_check_in_questions.png",
	"python_level_2_concept.png",
	"python_level_2_project.png",
	"python_level_3_concept.png",
	"python_level_3_project.png",
	"scratch_level_1_concept.png",
	"scratch_level_1_project.png",
	"scratch_level_2_concept.png",
	"scratch_level_2_project.png",
	"grs1_spirals.mp4",
	"grs1_turtle_exploration(1).mp4",
	"grs2_basic_shapes.mp4",
	"grs2_bullseye.mp4",
	"grs2_captain_american_shield.mp4",
	"grs2_minion.mp4",
	"grs2_more_shapes.mp4",
	"grs2_smiley_face.mp4",
	"grs2_taxi.mp4",
	"grs2_watermelon_slice.mp4",
	"grs3_awesome_angles.mp4",
	"grs3_debugging_practice.mp4",
	"grs3_random_bowtie.mp4",
	"grs3_random_walk.mp4",
	"grs3_surprise_me_square.mp4",
	"grs4_find_your_turtle.mp4",
	"grs4_fireworks.mp4",
	"grs4_into_the_void.mp4",
	"grs4_navigating_the_coordinate_plane.mp4",
	"grs4_out_of_the_void.mp4",
	"grs4_rainbow_ninja_star.mp4",
	"grs5_circle_of_circles.mp4",
	"grs5_pyramid.mp4",
	"grs5_rainbow_flower.mp4",
	"grs5_reverse_pyramid.mp4",
	"grs5_reverse_square_inception.mp4",
	"grs5_square_inception.mp4",
	"grs5_square_spiral.mp4",
	"grs6_dizzy_hexagon.mp4",
	"grs6_project_1.mp4",
	"grs6_project_2.mp4",
	"grs6_rainbow_square_inception.mp4",
	"grs6_randomly_random_shapes.mp4",
	"grs6_snowflake.mp4",
	"grs6_spiral_staircase.mp4",
	"grs7_any_shape_staircase.mp4",
	"grs7_debugging_functions.mp4",
	"grs7_project_1.mp4",
	"grs7_square_inception_with_functions.mp4",
	"grs7_winter_wonderland.gif",
	"grs7_zigzag.mp4",
	"grs8_etch_a_sketch.gif",
	"grs8_fruit_stand.gif",
	"grs8_picasso_game.gif",
	"grs8_polka_dot_game.gif",
	"grs8_project_1.mp4",
	"grs8_project_2.mp4",
	"grs8_project_3.mp4",
	"grs9_polkadots.mp4",
	"grs9_project_1.mp4",
	"grs9_random_age.gif",
	"grs9_surprise_shape.gif",
	"grs9_turtle_launch.gif",
	"grs9_turtle_race.gif",
	"grs10_bouncy_ball_room.gif",
	"grs10_debugging_practice.gif",
	"grs10_rainbow_path.gif",
	"grs10_random_number_lists.gif",
	"grs10_turtle_launch_with_lists.gif",
	"grs10_which_way_turtles.gif",
	"grs11_light_the_stars.gif",
	"grs11_project_1.mp4",
	"grs11_stay_inbounds.gif",
	"grs11_turtle_collision.gif",
	"grs12_fidget_spinner.gif",
	"grs12_list_exploration.mp4",
	"grs12_pong.gif",
	"grs12_snake.gif",
	"grs12_space_eater.gif",
	"grs12_target_practice.gif",
	"grs12_turtle_run.gif",
	"grs13_dodgeball.mp4",
	"grs13_fluid_motion.mp4",
	"grs13_perpetual_motion.mp4",
	"biomod1pro1im1.jpg",
	"biomod1pro1im2.jpg",
	"biomod2pro1im1.png",
	"c009b919-101b-4a4d-8f19-74885e8f62c0_Photosynthesis-01_577acc78_670x451.png",
	"api.png",
	"boxplot.png",
	"building_permits.csv",
	"categorical_variables.png",
	"cholera.csv",
	"data_science_concept.png",
	"data_science_project.png",
	"flight_delays.csv",
	"height_and_weight.csv",
	"ml3_1.png",
	"ml3_2.png",
	"mpg.csv",
	"normal.png",
	"palettes.png",
	"percents.png",
	"quantitative_variables.png",
	"sat.csv",
	"skew.png",
	"std.png",
	"tips.csv",
	"unemployment.csv",
	"us_county_incomes.csv",
	"zoo_animals.csv",
	"ent3_project2_0.png",
	"ent3_project2_1.png",
	"ent5_project1_0.png",
	"inv3_0.png",
	"jor2_disact_plotempty.png",
	"leb16_concept1_0.png",
	"mfb10_concept1_0.png",
	"module_project_1_0.png",
	"pf5_concept1_1.png",
	"pf5_concept1_2.png",
	"pf5_concept1_3.png",
	"pf5_concept1_4.png",
	"pf5_concept1_5.png",
	"pf5_concept1_6.png",
	"paa1_pset1_0.png",
	"paa_kickoff_0.png",
	"paa_kickoff_1.png",
	"pab5_0.png",
	"pab14_0.png",
	"pab22_0.png",
	"ted_ed_release.pdf",
	"UB1.png",
	"UB2.png",
	"UB3.png",
	"UB4.png",
	"UB5.png",
	"UB6.png",
	"missionTitle2.png",
	"nextStepTitle.png",
	"treasure.txt",
	"WhileLoopsExploration(1).mp4",
	"wyb1_proj1_plotempty.png"
] as const;

const knownPendingStaticMedia = new Set<string>(
	KNOWN_PENDING_STATIC_MEDIA_FILENAMES
);

function encodeStaticMediaCharacter(character: string) {
	return `%${character.charCodeAt(0).toString(16).toUpperCase()}`;
}

function staticMediaPathSegment(filename: string) {
	return encodeURIComponent(filename).replace(
		/[!'()*]/g,
		encodeStaticMediaCharacter
	);
}

export function staticMediaUrl(filename: string) {
	return `${STATIC_MEDIA_BASE}/${staticMediaPathSegment(filename)}`;
}

function trimStaticMediaUrl(url: string) {
	const trimmed = url.replace(/[.,;:!?]+$/g, "");
	return {
		trailing: url.slice(trimmed.length),
		url: trimmed
	};
}

export function staticMediaFilename(url: string) {
	try {
		const pathname = new URL(url).pathname;
		return decodeURIComponent(
			pathname.split("/").filter(Boolean).pop() || pathname || url
		);
	} catch {
		return url;
	}
}

export function isStaticMediaUrl(url: string) {
	try {
		return new URL(url).origin === STATIC_MEDIA_BASE;
	} catch {
		return false;
	}
}

export function isLegacyStaticMediaUrl(url: string) {
	try {
		return new URL(url).origin === LEGACY_STATIC_MEDIA_BASE;
	} catch {
		return false;
	}
}

export function canonicalStaticMediaUrl(url: string) {
	if (isStaticMediaUrl(url)) return url;
	if (isLegacyStaticMediaUrl(url))
		return staticMediaUrl(staticMediaFilename(url));
	return null;
}

export function isKnownPendingStaticMedia(filename: string) {
	return knownPendingStaticMedia.has(filename);
}

export function isKnownPendingStaticMediaUrl(url: string) {
	return (
		!!canonicalStaticMediaUrl(url) &&
		isKnownPendingStaticMedia(staticMediaFilename(url))
	);
}

export function staticMediaUrlsFromText(text: string) {
	return [...text.matchAll(STATIC_MEDIA_URL_PATTERN)]
		.map(match => trimStaticMediaUrl(match[0]).url)
		.map(canonicalStaticMediaUrl)
		.filter((url): url is string => Boolean(url));
}

export function normalizeStaticMediaUrlsInText(text: string) {
	return text.replace(STATIC_MEDIA_URL_PATTERN, rawUrl => {
		const { trailing, url } = trimStaticMediaUrl(rawUrl);
		return `${canonicalStaticMediaUrl(url) ?? url}${trailing}`;
	});
}

export function pendingStaticMediaNotice(filename: string) {
	return `**Pending media:** The file \`${filename}\` is not currently available. Space is reserved for it at ${staticMediaUrl(filename)} so the asset can be added later without changing this course link.`;
}

export function hasPendingStaticMediaNotice(content: string, filename: string) {
	return (
		content.includes(filename) &&
		content.includes(staticMediaUrl(filename)) &&
		PENDING_STATIC_MEDIA_NOTICE_PATTERN.test(content)
	);
}

export function withPendingStaticMediaNotice(
	content: string,
	filename: string
) {
	if (!isKnownPendingStaticMedia(filename)) {
		return content;
	}

	if (hasPendingStaticMediaNotice(content, filename)) {
		return content;
	}

	return `${content}\n\n${pendingStaticMediaNotice(filename)}`;
}
